version: "3.9"
services:
  ezlife-frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - VITE_APP_BACKEND_ADDRESS=${VITE_BACKEND_SERVICE_URL}
    container_name: ezlife-frontend-prod
    restart: always
    ports:
      - 5173:5173
    networks:
      - network
networks:
  network:
#docker-compose -f docker-compose-prod.yml up --build
